import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
  },
  headerTitle: {
    fontWeight: "700",
    color: "#2C3E50",
  },
  backButton: {
    padding: 8,
    marginLeft: 4,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  serviceCard: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#2C3E50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  serviceHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  serviceIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#EBF5FB",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  serviceInfo: {
    flex: 1,
  },
  brandText: {
    fontSize: 20,
    marginBottom: 2,
    color: "#2C3E50",
  },
  serviceTypeText: {
    fontSize: 15,
    color: "#7F8C8D",
  },
  priceTag: {
    backgroundColor: "#4A90E2",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  priceText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
  },
  userCard: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#2C3E50",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  userHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  userName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 2,
  },
  userEmail: {
    fontSize: 14,
    color: "#7F8C8D",
  },
  card: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#2C3E50",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 16,
    color: "#2C3E50",
    marginLeft: 8,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1.5,
    borderColor: "#E8E8E8",
    borderRadius: 12,
    padding: 16,
    fontSize: 15,
    minHeight: 120,
    backgroundColor: "#FBFCFC",
    textAlignVertical: "top",
    color: "#2C3E50",
  },
  charCounter: {
    alignItems: "flex-end",
    marginTop: 8,
  },
  charText: {
    fontSize: 12,
    color: "#95A5A6",
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E8E8E8",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#FBFCFC",
  },
  dateText: {
    flex: 1,
    marginLeft: 12,
    fontSize: 15,
    color: "#2C3E50",
  },
  todayBadge: {
    backgroundColor: "#E8F6F3",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  todayText: {
    fontSize: 12,
    color: "#1ABC9C",
    fontWeight: "600",
  },
  timeSlotsContainer: {
    paddingVertical: 4,
    gap: 8,
  },
  timeSlot: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#E8E8E8",
    backgroundColor: "#FBFCFC",
    minWidth: 100,
    alignItems: "center",
  },
  timeSlotSelected: {
    backgroundColor: "#4A90E2",
    borderColor: "#4A90E2",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  timeSlotText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7F8C8D",
  },
  timeSlotTextSelected: {
    color: "#FFFFFF",
  },
  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#2C3E50",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },
  summaryContent: {
    padding: 20,
    paddingTop: 0,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 14,
    color: "#7F8C8D",
  },
  summaryValue: {
    fontSize: 14,
    color: "#2C3E50",
    fontWeight: "500",
    textAlign: "right",
    flex: 1,
    marginLeft: 8,
  },
  divider: {
    height: 1,
    backgroundColor: "#ECF0F1",
    marginVertical: 12,
  },
  totalLabel: {
    fontSize: 16,
    color: "#2C3E50",
  },
  totalValue: {
    fontSize: 18,
    color: "#4A90E2",
  },
  bookButton: {
    backgroundColor: "#4A90E2",
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 6,
  },
  bookButtonDisabled: {
    backgroundColor: "#BDC3C7",
    shadowColor: "#95A5A6",
    shadowOpacity: 0.1,
  },
  bookButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  footerNote: {
    paddingHorizontal: 8,
  },
  footerText: {
    fontSize: 13,
    color: "#7F8C8D",
    textAlign: "center",
    lineHeight: 18,
  },
});

export const timeSlots = [
  '09:00 AM', '10:00 AM', '11:00 AM', 
  '01:00 PM', '02:00 PM', '03:00 PM', '04:00 PM'
];
